# Generated by Django 2.0.5 on 2018-05-25 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('name', models.AutoField(max_length=50, primary_key=True, serialize=False)),
                ('content', models.TextField(max_length=5000)),
            ],
        ),
    ]
